INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Fan House in Downtown", "This house located in downtown Richmond is only a 15 minute walk to VCU and centrally located to dozens of anemities and close to three parks and walking and biking trails", 400, 2, 2, 1, 0, "Richmond", "Kemper St at Randolph", "Angela Shrute", "804-555-5000", "https://www.crashpad.com/images/attribute/apt2.jpg", "https://dbv47yu57n5vf.cloudfront.net/s3fs-public/nice2(1).jpg", "http://www.medmoot.net/wp-content/uploads/2017/07/h2.jpg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Landmark Lifestyle Apartments", "Vintage-styled apartments are centrally located, have classic wooden floors, and are within walking distance to everything!", 700, 1, 2, 1, 0, "Richmond", "900 West Franklin Street", "Feinstein Inc", "804-555-1234", "https://07f138315bb5e97f9e43-31068357019044cca7c8e84d92de0d99.ssl.cf3.rackcdn.com/1024x768/56587_11491_001.jpg", "https://2e04f91eb4f37516324c-f47ac95ea68e17b39c6e95ff0fa62fe6.ssl.cf3.rackcdn.com/1024x768/53527_2779_00.jpg", "https://c50039.ssl.cf3.rackcdn.com/uploads/photo/file/42580235/default.jpg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Cary Street Room", "The whole house is available for rent by room, has a washer and dryer, and on-site parking", 700, 2, 2, 1, 0, "Richmond", "1233 West Cary Street", "April Ludgate", "804-555-5432", "https://res.cloudinary.com/apartmentlist/image/upload/s--HRoGG_hz--/t_web-base/c_fill,g_auto,h_1016,w_2400/c_scale,w_2400/v1/web/static/hero_living_room.jpg", "http://o794seclxk3k88av45t66i12-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/Penthouse-Rathbone-Square-e1485709140836.jpg", "https://cdn.vox-cdn.com/thumbor/E0jNRUTI81RBBRMSA_ZU7vq7I4g=/0x0:2400x1602/1200x675/filters:focal(682x772:1066x1156)/cdn.vox-cdn.com/uploads/chorus_image/image/54241701/LINEA_NicholasJamesPhoto_8.0.jpeg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Moseley Detached House", "This downtown house needs a female roomate for 2 current occupants. Live in style close to the river!", 700, 2, 2, 1, 0,"Richmond", "Moseley St", "Maurice Moss", "804-555-0000", "https://www.londonperfect.com/g/apartment-hero-images/hi_eldon-apartment-rental-16.jpg", "https://images.central-london-apartments.com/property/4746/image/9091_1_9551_d0fcdfe752ad4c1a0d641ccbce670419.jpg", "https://cdn.freshome.com/wp-content/uploads/2008/03/apartment.jpg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Private Room Single Family House", "Stay however long or short you need in this single-family home in Eastern Henrico.", 600, 3, 2, 1, 0, "East Henrico", "Featherwood Way at Creighton Road", "Gary Gergich", "804-555-1365", "http://www.apartmentsonhoneysuckle.com/wp-content/uploads/2018/03/Apartment.jpg", "http://writingfortheweb.co/wp-content/uploads/2017/11/design-home-com-delectable-architecture-italian-home-800x450.jpg", "http://illinoisdouble.com/wp-content/uploads/modern-apartments-modern-apartment-decor-ideas-unbelievable-minimalist-theme-for.jpg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Single Bed in Manchester", "Undergrad students welcome! All utilities are included, and we're close to the river!", 600, 1, 2, 0, 1, "Richmond", "Perry Street", "Dunder Mifflin", "804-555-9876", "https://dynaimage.cdn.cnn.com/cnn/q_auto,w_1024,c_fill,g_auto,h_576,ar_16:9/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F171011112316-worlds-best-apartment-hotels-1--aka-beverly-2.jpg", "https://cdn.gearpatrol.com/wp-content/uploads/2015/08/Apartment-Apps-Gear-Patrol-Lead-Full.jpg", "http://slmdesigninteriors.com/media/upload/fancy-apartment-interior-design-white-apartment-interior-design-showcase.jpg");

INSERT INTO sublet (title, [description], rent, roommates, baths, female, male, city, [location], landlord, managementContactInfo, imageOne, imageTwo, imageThree, imageFour) values ("Master Bedroom in Private Home", "Rent the large master bedroom in a quiet home in a quiet neighborhood. All utilities are included, and W&D are on site", 700, 3, 2.5, 1, 1, "Richmond", "Pump Road", "Maurice Moss", "804-555-0000", "http://www.connectorcountry.com/wp-content/uploads/2017/09/classic-greenwich-village-apartment-homes-of-interior-designers-nyc-tours-my-sqft-tour-an-designer-s-design-living.jpg", "https://media.architecturaldigest.com/photos/58505bf0dcb583e908275b2f/master/pass/Adam-Lippes_03.jpg", "http://4.bp.blogspot.com/-URV_EWsZ5dw/T3nb56qh6uI/AAAAAAABAhg/zZcLKWuAC38/s1600/2_JackPierson2_gr.jpg");